name: TaxPlugin
version: '1.0-SNAPSHOT'
main: com.taxPlugin.TaxPlugin
api-version: '1.19'
depend: [Vault]
description: A plugin that taxes players 4% of their balance every 2 hours
commands:
  tax:
    description: Tax plugin commands
    usage: /<command> [info]
    permission: taxplugin.admin
permissions:
  taxplugin.admin:
    description: Allows access to tax admin commands
    default: op
  taxplugin.exempt:
    description: Exempts players from taxation
    default: false 